[DEBUG] 2024-03-28 GMT-0400 09:01:35.432: The Username is set to (keyring app): cody.bogausch@sunycgcc.edu
[DEBUG] 2024-03-28 GMT-0400 09:01:35.434: The Submission Password is set to (keyring app): ***
[INFO] 2024-03-28 GMT-0400 09:01:35.435: Submission process STARTED.
[INFO] 2024-03-28 GMT-0400 09:01:35.435: Asking for agreement.
[DEBUG] 2024-03-28 GMT-0400 09:01:39.341: Agreement answer: I AGREE
[DEBUG] 2024-03-28 GMT-0400 09:01:39.341: Task signature: sail2-project-author-classes-o-hcjnaayu-v2-bf0a22c6-631b-4d8d-93a5-b6f9dc4b5ecd
[INFO] 2024-03-28 GMT-0400 09:01:39.341: Collecting information about context.
[INFO] 2024-03-28 GMT-0400 09:01:39.406: Finding files for submission.
[INFO] 2024-03-28 GMT-0400 09:01:39.406: Generating submission files for task 5.
[INFO] 2024-03-28 GMT-0400 09:01:39.406: Evaluating task 5.
[ERROR] 2024-03-28 GMT-0400 09:01:39.472: An unexpected error has occurred.
Traceback (most recent call last):
  File "<string>", line 70, in run
  File "<string>", line 32, in generate_submission_archive
  File "/usr/local/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/lib/python3.8/tarfile.py", line 2141, in add
    tarinfo = self.gettarinfo(name, arcname)
  File "/usr/local/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/lib/python3.8/tarfile.py", line 2014, in gettarinfo
    statres = os.lstat(name)
FileNotFoundError: [Errno 2] No such file or directory: 'shapes_example.py'
[INFO] 2024-03-28 GMT-0400 09:01:39.473: Finding files for cleanup.
[INFO] 2024-03-28 GMT-0400 09:01:39.473: Cleanup finished.
[INFO] 2024-03-28 GMT-0400 09:01:39.473: Submission process FINISHED.
